[package]
name = "kalman-filter-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.30.0"
poloto = "3.11.1"
rand = "0.8.4"
rand_distr = "0.4.2"
